# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscBeta < Formula
  desc "AWS Simple CLI (ASC) - A simplified interface for AWS operations. (Beta channel)"
  homepage "https://github.com/harleymckenzie/asc"
  version "0.4.0-beta.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/asc/releases/download/v0.4.0-beta.1/asc_Darwin_x86_64.tar.gz"
    sha256 "c1dfee9fa61341c39c3e9807787519f92bd0cf47ebbf6ec1c34f8ca05398065e"

    define_method(:install) do
      bin.install "asc"
      generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/asc/releases/download/v0.4.0-beta.1/asc_Darwin_arm64.tar.gz"
    sha256 "67fb1c0adfedaa1403db9aecf242f3127e044f2746a29dfeab272c81748d1fd6"

    define_method(:install) do
      bin.install "asc"
      generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
