# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscGo < Formula
  desc "AWS CLI tool for managing AWS resources."
  homepage "https://github.com/harleymckenzie/asc-go"
  version "1.1.1"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_x86_64.tar.gz"
    sha256 "f868427cbef3d0538999507b61c92c4b927bc06569c45b6ac5cee557327ecd05"

    def install
      bin.install "asc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_arm64.tar.gz"
    sha256 "594ad7322a7fd6ddbfb346b8d8822ec2ab1165b21623832336b27276c5af1a66"

    def install
      bin.install "asc"
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
