# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscGo < Formula
  desc "AWS CLI tool for managing AWS resources."
  homepage "https://github.com/harleymckenzie/asc-go"
  version "1.1.1"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_x86_64.tar.gz"
    sha256 "43d6ed7782589072e8e6850c1fe6cfd873ead0eff2471875605b8596835a62cf"

    def install
      bin.install "asc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_arm64.tar.gz"
    sha256 "37afa74ed7c746e9fac781415f8b41bdf9c9f12c994da039f50900d0fec83722"

    def install
      bin.install "asc"
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
