# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscBeta < Formula
  desc "AWS Simple CLI (ASC) - A simplified interface for AWS operations. (Beta channel)"
  homepage "https://github.com/harleymckenzie/asc"
  version "0.0.38-beta.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/asc/releases/download/v0.0.38-beta.4/asc_Darwin_x86_64.tar.gz"
    sha256 "baa7a79532195f6d751c2cd63d4212fa7c2f9d5522bd0bcf885a1234b5dc797e"

    def install
      bin.install "asc"
      generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/asc/releases/download/v0.0.38-beta.4/asc_Darwin_arm64.tar.gz"
    sha256 "edff268c37c1e750cba4efc68b339fafabaae579133fc3aba7641fb9f7ed7a7e"

    def install
      bin.install "asc"
      generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
