# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscGo < Formula
  desc "AWS CLI tool for managing AWS resources."
  homepage "https://github.com/harleymckenzie/asc-go"
  version "1.1.1"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_x86_64.tar.gz"
    sha256 "c5d3a236adbaa33758a04238bc8eb9a3a92cdfea6c1f12c5571946872b696b7e"

    def install
      bin.install "asc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_arm64.tar.gz"
    sha256 "bf6b187ef39a8e4414c09e0253d6c02798a58383423c2fd20b656319330ff884"

    def install
      bin.install "asc"
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
