# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asc < Formula
  desc "AWS Simple CLI (ASC) - A simplified interface for AWS operations."
  homepage "https://github.com/harleymckenzie/asc"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harleymckenzie/asc/releases/download/v0.0.10/asc_Darwin_x86_64.tar.gz"
      sha256 "22249eb07004730cf43bb7fc3fd8ba9329793585057fcbf597dfce5d923ec060"

      def install
        bin.install "asc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harleymckenzie/asc/releases/download/v0.0.10/asc_Darwin_arm64.tar.gz"
      sha256 "f5312261f210bd6727bda3f1522d25d4cc1f886bd14c4ae8f77106e9bfc9b719"

      def install
        bin.install "asc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harleymckenzie/asc/releases/download/v0.0.10/asc_Linux_x86_64.tar.gz"
        sha256 "8e8525b98904191670c8e715115690deea6f631d0ad31af909461e44a48d7b1b"

        def install
          bin.install "asc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harleymckenzie/asc/releases/download/v0.0.10/asc_Linux_arm64.tar.gz"
        sha256 "ed94cc90b6e1769f25a8c1f89c68a09ead889e9c0c30f55566f953d715250e24"

        def install
          bin.install "asc"
        end
      end
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
