# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asc < Formula
  desc "AWS Simple CLI (ASC) - A simplified interface for AWS operations."
  homepage "https://github.com/harleymckenzie/asc"
  version "0.0.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harleymckenzie/asc/releases/download/v0.0.19/asc_Darwin_x86_64.tar.gz"
      sha256 "5c643e41bf045604ee718be38ea21346fe258657b1eb1cfbdcef32fe1f4384e6"

      def install
        bin.install "asc"
        generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harleymckenzie/asc/releases/download/v0.0.19/asc_Darwin_arm64.tar.gz"
      sha256 "a96da892638cf3d1292c6b1e2d51a2642e592f78ab16525d028d93292b257cff"

      def install
        bin.install "asc"
        generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/harleymckenzie/asc/releases/download/v0.0.19/asc_Linux_x86_64.tar.gz"
      sha256 "d1a55113e483eb17130c3593f43e3312b84789ffa43c74c2055618959ce96ac7"
      def install
        bin.install "asc"
        generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/harleymckenzie/asc/releases/download/v0.0.19/asc_Linux_arm64.tar.gz"
      sha256 "6cc1ae3c79e301c8b02ec7e97db28713df85d3ea7418dc573858c197a86d52c3"
      def install
        bin.install "asc"
        generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
