# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assm < Formula
  desc "A CLI designed to provide a more simplified way to connect to EC2 instances using via AWS Systems Manager Sessions Manager."
  homepage "https://github.com/harleymckenzie/assm"
  version "0.0.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/assm/releases/download/v0.0.4/assm_Darwin_x86_64.tar.gz"
    sha256 "20dc29925b9ede3c157d75821b79dbd59486e661cf4e2d7126859ffe5cef94bd"

    def install
      bin.install "assm"
      generate_completions_from_executable(bin/"assm", "completion", shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/assm/releases/download/v0.0.4/assm_Darwin_arm64.tar.gz"
    sha256 "46861dbb69f6dc34aab7b55bd2b2e51d8e6ec0b9c43b9605ec2a7994e1a7dd58"

    def install
      bin.install "assm"
      generate_completions_from_executable(bin/"assm", "completion", shells: [:bash, :zsh, :fish])
    end
  end

  test do
    system "#{bin}/assm --help"
  end
end
