# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assm < Formula
  desc "A CLI designed to provide a more simplified way to connect to EC2 instances using via AWS Systems Manager Sessions Manager."
  homepage "https://github.com/harleymckenzie/assm"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/assm/releases/download/v0.0.1/assm_Darwin_x86_64.tar.gz"
    sha256 "4afd196e66a434648bf1bb6b6d84ce286e4a84b01fd45fd8409769cafab877fb"

    def install
      bin.install "assm"
      generate_completions_from_executable(bin/"assm", "completion", shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/assm/releases/download/v0.0.1/assm_Darwin_arm64.tar.gz"
    sha256 "54b0de1fb351d7d25481aea155f29035bda87f69c9b2ae928936a4dccfafe578"

    def install
      bin.install "assm"
      generate_completions_from_executable(bin/"assm", "completion", shells: [:bash, :zsh, :fish])
    end
  end

  test do
    system "#{bin}/assm help"
  end
end
