# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assm < Formula
  desc "A CLI designed to provide a more simplified way to connect to EC2 instances using via AWS Systems Manager Sessions Manager."
  homepage "https://github.com/harleymckenzie/assm"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/assm/releases/download/v0.1.0/assm_Darwin_x86_64.tar.gz"
    sha256 "274b66f1e1901e0225a3a6dcf6ccdc776ebb3ace97da83cd840cb18c28062c19"

    define_method(:install) do
      bin.install "assm"
      generate_completions_from_executable(bin/"assm", "completion", shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/assm/releases/download/v0.1.0/assm_Darwin_arm64.tar.gz"
    sha256 "c97a8ba019cb5a9632c50452c4d329cdfebd0133c94bb1eafa8476cd7faed246"

    define_method(:install) do
      bin.install "assm"
      generate_completions_from_executable(bin/"assm", "completion", shells: [:bash, :zsh, :fish])
    end
  end

  test do
    system "#{bin}/assm --help"
  end
end
