name: Update Homebrew Formula

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests hashlib

      - name: Update formula
        id: release_info
        run: |
          python update_formula.py
          echo ::set-output name=tag_name::$(python -c "import json; print(json.load(open('release_info.json'))['tag_name'])")
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/asc.rb
          git commit -m "Update formula to ${{ env.VERSION }}"
          git push
