name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      project:
        description: "The project to update"
        required: true
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create project output
        id: project
        run: |
          if [[ "${{ github.event.inputs.project }}" == "" ]]; then
            echo "Using project from event payload"
            project="${{ github.event.client_payload.project }}"
            echo "Project: $project"
            echo "project=$project" >> $GITHUB_OUTPUT
          else
            echo "Using project from input"
            project="${{ github.event.inputs.project }}"
            echo "Project: $project"
            echo "project=$project" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Update formula
        run: python update-formula.py ${{ steps.project.outputs.project }}

      - name: Commit and push changes
        run: |
          project=${{ steps.project.outputs.project }}
          filename=Formula/$project.rb
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $filename
          git commit -m "Update $project Formula"
          git push
